title: Anatoly Levkovich # your name (or website title) here
logo: "/images/portrait.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AAS in Web Design & Development 
  <br><br>
  Looking for an entry level position in the Web Design/Development field! 
  <br><br>
  <a href="https://www.linkedin.com/in/anatoly-levkovich-740a17195/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
